/// <mls fileReference="_102051_/l2/layout/appHeader.ts" enhancement="_blank" />

// Project header generated by agentGenerateHeader (_102020_/l2/aura/agentManageHeader).
//
// The band, its fixed height, the brand, the mobile aside toggle and SPA navigation all come
// from AuraHeaderBase — this file only fills the band. The brand lives in the config profile
// (clientShell.regions.header.profiles[...].brand), so regenerating this file cannot lose it.

import { html } from 'lit';
import { AuraHeaderBase } from '/_102033_/l2/shared/layout/aura-header-base.js';

/// **collab_i18n_start**
const message_pt = {
  welcome: "Bem-vindo",
};
type MessageType = typeof message_pt;
const messages: Record<string, MessageType> = {
  pt: message_pt,
  en: {
    welcome: "Welcome",
  },
};
/// **collab_i18n_end**

export class AppHeader102051 extends AuraHeaderBase {
  protected bandCss(): string {
    const tag = this.localName;
    return `
${tag} {
  display: block;
}

${tag} .app-header-left,
${tag} .app-header-right {
  min-width: 0;
  gap: var(--space-16, 16px);
}

${tag} .app-header-right {
  justify-content: flex-end;
}

${tag} .app-header-brand-custom {
  display: flex;
  align-items: center;
  min-width: 0;
  gap: var(--space-8, 8px);
}

${tag} .app-header-brand-copy {
  display: flex;
  flex-direction: column;
  min-width: 0;
  overflow: hidden;
}

${tag} .app-header-ticker-title {
  display: inline-block;
  width: 0;
  overflow: hidden;
  white-space: nowrap;
  color: var(--nav-active-text, #102a43);
  animation: app-header-ticker-102051 1.8s steps(10, end) forwards;
}

${tag} .app-header-ticker-subtitle {
  opacity: 0;
  animation: app-header-subtitle-102051 var(--transition-normal, 240ms) ease-out 1.8s forwards;
}

${tag} .app-header-welcome {
  min-width: 0;
  overflow: hidden;
  color: var(--nav-text, #102a43);
  font-family: var(--font-family-primary, sans-serif);
  font-size: var(--font-size-16, 16px);
  font-weight: var(--font-weight-normal, 400);
  line-height: var(--line-height-medium, 1.4);
  text-align: center;
  text-overflow: ellipsis;
  white-space: nowrap;
}

@keyframes app-header-ticker-102051 {
  from { width: 0; }
  to { width: 100%; }
}

@keyframes app-header-subtitle-102051 {
  from { opacity: 0; transform: translateY(2px); }
  to { opacity: 1; transform: translateY(0); }
}

@media (prefers-reduced-motion: reduce) {
  ${tag} .app-header-ticker-title {
    width: auto;
    animation: none;
  }

  ${tag} .app-header-ticker-subtitle {
    opacity: 1;
    animation: none;
  }
}

@media (max-width: 720px) {
  ${tag} {
    grid-template-columns: minmax(0, 1fr) auto;
    gap: var(--space-8, 8px);
  }

  ${tag} .app-header-welcome {
    display: none;
  }
}
`;
  }

  protected renderBand() {
    return html`
      <div class="aura-header-side app-header-left">
        ${this.renderAsideToggle()}
        <div class="app-header-brand-custom">
          ${this.renderLogo()}
          <div class="app-header-brand-copy">
            <span class="aura-header-title app-header-ticker-title">${this.brand.title}</span>
            <span class="aura-header-subtitle app-header-ticker-subtitle">${this.brand.subtitle}</span>
          </div>
        </div>
      </div>
      <div class="app-header-welcome" aria-live="polite">
        ${this.localized(messages).welcome}${this.userFirstName ? `, ${this.userFirstName}` : ''}
      </div>
      <div class="aura-header-side app-header-right">
        ${this.renderActions()}
        ${this.renderUserAvatar()}
      </div>
    `;
  }
}

customElements.define('layout--app-header-102051', AppHeader102051);
