/// <mls fileReference="_102051_/l2/cafeFlow/web/shared/menuManagement.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowMenuManagementBase } from '/_102051_/l2/cafeFlow/web/shared/menuManagement.js';
import type { CreateMenuItemCmdInput, CreateMenuItemCmdOutput, ListMenuItemsInput, ListMenuItemsOutput, UpdateMenuItemCmdInput, UpdateMenuItemCmdOutput } from '/_102051_/l2/cafeFlow/web/contracts/menuManagement.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowMenuManagementBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_listMenuItemsState = Assert<Assignable<typeof page.listMenuItemsState, "idle" | "loading" | "success" | "error">>;
type _State_listMenuItemsStatus = Assert<Assignable<typeof page.listMenuItemsStatus, string | ListMenuItemsInput["status"]>>;
type _State_listMenuItemsMenuCategoryId = Assert<Assignable<typeof page.listMenuItemsMenuCategoryId, string | ListMenuItemsInput["menuCategoryId"]>>;
type _State_listMenuItemsName = Assert<Assignable<typeof page.listMenuItemsName, string | ListMenuItemsInput["name"]>>;
type _State_listMenuItemsPage = Assert<Assignable<typeof page.listMenuItemsPage, string | ListMenuItemsInput["page"]>>;
type _State_listMenuItemsPageSize = Assert<Assignable<typeof page.listMenuItemsPageSize, string | ListMenuItemsInput["pageSize"]>>;
type _State_listMenuItemsData = Assert<Assignable<typeof page.listMenuItemsData, ListMenuItemsOutput>>;
type _State_createMenuItemCmdState = Assert<Assignable<typeof page.createMenuItemCmdState, "idle" | "loading" | "success" | "error">>;
type _State_createMenuItemCmdMenuCategoryId = Assert<Assignable<typeof page.createMenuItemCmdMenuCategoryId, string | CreateMenuItemCmdInput["menuCategoryId"]>>;
type _State_createMenuItemCmdName = Assert<Assignable<typeof page.createMenuItemCmdName, string | CreateMenuItemCmdInput["name"]>>;
type _State_createMenuItemCmdDescription = Assert<Assignable<typeof page.createMenuItemCmdDescription, string | CreateMenuItemCmdInput["description"]>>;
type _State_createMenuItemCmdPrice = Assert<Assignable<typeof page.createMenuItemCmdPrice, string | CreateMenuItemCmdInput["price"]>>;
type _State_createMenuItemCmdStatus = Assert<Assignable<typeof page.createMenuItemCmdStatus, string | CreateMenuItemCmdInput["status"]>>;
type _State_createMenuItemCmdImageUrl = Assert<Assignable<typeof page.createMenuItemCmdImageUrl, string | CreateMenuItemCmdInput["imageUrl"]>>;
type _State_createMenuItemCmdDisplayOrder = Assert<Assignable<typeof page.createMenuItemCmdDisplayOrder, string | CreateMenuItemCmdInput["displayOrder"]>>;
type _State_createMenuItemCmdRequiresStockLink = Assert<Assignable<typeof page.createMenuItemCmdRequiresStockLink, string | CreateMenuItemCmdInput["requiresStockLink"]>>;
type _State_createMenuItemCmdOutput = Assert<Assignable<typeof page.createMenuItemCmdOutput, CreateMenuItemCmdOutput | null>>;
type _State_createMenuItemCmdError = Assert<Assignable<typeof page.createMenuItemCmdError, string>>;
type _State_updateMenuItemCmdState = Assert<Assignable<typeof page.updateMenuItemCmdState, "idle" | "loading" | "success" | "error">>;
type _State_updateMenuItemCmdMenuItemId = Assert<Assignable<typeof page.updateMenuItemCmdMenuItemId, string | UpdateMenuItemCmdInput["menuItemId"]>>;
type _State_updateMenuItemCmdMenuCategoryId = Assert<Assignable<typeof page.updateMenuItemCmdMenuCategoryId, string | UpdateMenuItemCmdInput["menuCategoryId"]>>;
type _State_updateMenuItemCmdName = Assert<Assignable<typeof page.updateMenuItemCmdName, string | UpdateMenuItemCmdInput["name"]>>;
type _State_updateMenuItemCmdDescription = Assert<Assignable<typeof page.updateMenuItemCmdDescription, string | UpdateMenuItemCmdInput["description"]>>;
type _State_updateMenuItemCmdPrice = Assert<Assignable<typeof page.updateMenuItemCmdPrice, string | UpdateMenuItemCmdInput["price"]>>;
type _State_updateMenuItemCmdStatus = Assert<Assignable<typeof page.updateMenuItemCmdStatus, string | UpdateMenuItemCmdInput["status"]>>;
type _State_updateMenuItemCmdPauseReason = Assert<Assignable<typeof page.updateMenuItemCmdPauseReason, string | UpdateMenuItemCmdInput["pauseReason"]>>;
type _State_updateMenuItemCmdImageUrl = Assert<Assignable<typeof page.updateMenuItemCmdImageUrl, string | UpdateMenuItemCmdInput["imageUrl"]>>;
type _State_updateMenuItemCmdDisplayOrder = Assert<Assignable<typeof page.updateMenuItemCmdDisplayOrder, string | UpdateMenuItemCmdInput["displayOrder"]>>;
type _State_updateMenuItemCmdRequiresStockLink = Assert<Assignable<typeof page.updateMenuItemCmdRequiresStockLink, string | UpdateMenuItemCmdInput["requiresStockLink"]>>;
type _State_updateMenuItemCmdOutput = Assert<Assignable<typeof page.updateMenuItemCmdOutput, UpdateMenuItemCmdOutput | null>>;
type _State_updateMenuItemCmdError = Assert<Assignable<typeof page.updateMenuItemCmdError, string>>;
type _Action_loadListMenuItems = Assert<Assignable<typeof page.loadListMenuItems, (...args: any[]) => unknown>>;
type _Handler_handleListMenuItemsClick = Assert<Assignable<typeof page.handleListMenuItemsClick, (...args: any[]) => unknown>>;
type _Action_createMenuItemCmd = Assert<Assignable<typeof page.createMenuItemCmd, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdClick = Assert<Assignable<typeof page.handleCreateMenuItemCmdClick, (...args: any[]) => unknown>>;
type _Action_updateMenuItemCmd = Assert<Assignable<typeof page.updateMenuItemCmd, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdClick = Assert<Assignable<typeof page.handleUpdateMenuItemCmdClick, (...args: any[]) => unknown>>;
type _Action_setListMenuItemsStatus = Assert<Assignable<typeof page.setListMenuItemsStatus, (...args: any[]) => unknown>>;
type _Handler_handleListMenuItemsStatusChange = Assert<Assignable<typeof page.handleListMenuItemsStatusChange, (...args: any[]) => unknown>>;
type _Action_setListMenuItemsMenuCategoryId = Assert<Assignable<typeof page.setListMenuItemsMenuCategoryId, (...args: any[]) => unknown>>;
type _Handler_handleListMenuItemsMenuCategoryIdChange = Assert<Assignable<typeof page.handleListMenuItemsMenuCategoryIdChange, (...args: any[]) => unknown>>;
type _Action_setListMenuItemsName = Assert<Assignable<typeof page.setListMenuItemsName, (...args: any[]) => unknown>>;
type _Handler_handleListMenuItemsNameChange = Assert<Assignable<typeof page.handleListMenuItemsNameChange, (...args: any[]) => unknown>>;
type _Action_setListMenuItemsPage = Assert<Assignable<typeof page.setListMenuItemsPage, (...args: any[]) => unknown>>;
type _Handler_handleListMenuItemsPageChange = Assert<Assignable<typeof page.handleListMenuItemsPageChange, (...args: any[]) => unknown>>;
type _Action_setListMenuItemsPageSize = Assert<Assignable<typeof page.setListMenuItemsPageSize, (...args: any[]) => unknown>>;
type _Handler_handleListMenuItemsPageSizeChange = Assert<Assignable<typeof page.handleListMenuItemsPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdMenuCategoryId = Assert<Assignable<typeof page.setCreateMenuItemCmdMenuCategoryId, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdMenuCategoryIdChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdMenuCategoryIdChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdName = Assert<Assignable<typeof page.setCreateMenuItemCmdName, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdNameChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdNameChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdDescription = Assert<Assignable<typeof page.setCreateMenuItemCmdDescription, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdDescriptionChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdPrice = Assert<Assignable<typeof page.setCreateMenuItemCmdPrice, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdPriceChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdPriceChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdStatus = Assert<Assignable<typeof page.setCreateMenuItemCmdStatus, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdStatusChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdStatusChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdImageUrl = Assert<Assignable<typeof page.setCreateMenuItemCmdImageUrl, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdImageUrlChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdImageUrlChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdDisplayOrder = Assert<Assignable<typeof page.setCreateMenuItemCmdDisplayOrder, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdDisplayOrderChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdDisplayOrderChange, (...args: any[]) => unknown>>;
type _Action_setCreateMenuItemCmdRequiresStockLink = Assert<Assignable<typeof page.setCreateMenuItemCmdRequiresStockLink, (...args: any[]) => unknown>>;
type _Handler_handleCreateMenuItemCmdRequiresStockLinkChange = Assert<Assignable<typeof page.handleCreateMenuItemCmdRequiresStockLinkChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdMenuItemId = Assert<Assignable<typeof page.setUpdateMenuItemCmdMenuItemId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdMenuItemIdChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdMenuItemIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdMenuCategoryId = Assert<Assignable<typeof page.setUpdateMenuItemCmdMenuCategoryId, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdMenuCategoryIdChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdMenuCategoryIdChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdName = Assert<Assignable<typeof page.setUpdateMenuItemCmdName, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdNameChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdNameChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdDescription = Assert<Assignable<typeof page.setUpdateMenuItemCmdDescription, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdDescriptionChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdPrice = Assert<Assignable<typeof page.setUpdateMenuItemCmdPrice, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdPriceChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdPriceChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdStatus = Assert<Assignable<typeof page.setUpdateMenuItemCmdStatus, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdStatusChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdStatusChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdPauseReason = Assert<Assignable<typeof page.setUpdateMenuItemCmdPauseReason, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdPauseReasonChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdPauseReasonChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdImageUrl = Assert<Assignable<typeof page.setUpdateMenuItemCmdImageUrl, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdImageUrlChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdImageUrlChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdDisplayOrder = Assert<Assignable<typeof page.setUpdateMenuItemCmdDisplayOrder, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdDisplayOrderChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdDisplayOrderChange, (...args: any[]) => unknown>>;
type _Action_setUpdateMenuItemCmdRequiresStockLink = Assert<Assignable<typeof page.setUpdateMenuItemCmdRequiresStockLink, (...args: any[]) => unknown>>;
type _Handler_handleUpdateMenuItemCmdRequiresStockLinkChange = Assert<Assignable<typeof page.handleUpdateMenuItemCmdRequiresStockLinkChange, (...args: any[]) => unknown>>;

export {};