/// <mls fileReference="_102051_/l2/cafeFlow/web/shared/posWorkspace.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowPosWorkspaceBase } from '/_102051_/l2/cafeFlow/web/shared/posWorkspace.js';
import type { CmdCreateOrderInput, CmdCreateOrderOutput, CmdRecordBasicPaymentInput, CmdRecordBasicPaymentOutput, CmdUpdateOrderStatusInput, CmdUpdateOrderStatusOutput, QueryMenuItemsInput, QueryMenuItemsOutput, QueryOpenOrdersInput, QueryOpenOrdersOutput } from '/_102051_/l2/cafeFlow/web/contracts/posWorkspace.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowPosWorkspaceBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_queryOpenOrdersState = Assert<Assignable<typeof page.queryOpenOrdersState, "idle" | "loading" | "success" | "error">>;
type _State_queryOpenOrdersDailyShiftId = Assert<Assignable<typeof page.queryOpenOrdersDailyShiftId, string | QueryOpenOrdersInput["dailyShiftId"]>>;
type _State_queryOpenOrdersStatus = Assert<Assignable<typeof page.queryOpenOrdersStatus, string | QueryOpenOrdersInput["status"]>>;
type _State_queryOpenOrdersOrderType = Assert<Assignable<typeof page.queryOpenOrdersOrderType, string | QueryOpenOrdersInput["orderType"]>>;
type _State_queryOpenOrdersTableNumber = Assert<Assignable<typeof page.queryOpenOrdersTableNumber, string | QueryOpenOrdersInput["tableNumber"]>>;
type _State_queryOpenOrdersPage = Assert<Assignable<typeof page.queryOpenOrdersPage, string | QueryOpenOrdersInput["page"]>>;
type _State_queryOpenOrdersPageSize = Assert<Assignable<typeof page.queryOpenOrdersPageSize, string | QueryOpenOrdersInput["pageSize"]>>;
type _State_queryOpenOrdersData = Assert<Assignable<typeof page.queryOpenOrdersData, QueryOpenOrdersOutput>>;
type _State_queryMenuItemsState = Assert<Assignable<typeof page.queryMenuItemsState, "idle" | "loading" | "success" | "error">>;
type _State_queryMenuItemsMenuCategoryId = Assert<Assignable<typeof page.queryMenuItemsMenuCategoryId, string | QueryMenuItemsInput["menuCategoryId"]>>;
type _State_queryMenuItemsData = Assert<Assignable<typeof page.queryMenuItemsData, unknown[] | QueryMenuItemsOutput>>;
type _State_cmdCreateOrderState = Assert<Assignable<typeof page.cmdCreateOrderState, "idle" | "loading" | "success" | "error">>;
type _State_cmdCreateOrderOrderType = Assert<Assignable<typeof page.cmdCreateOrderOrderType, string | CmdCreateOrderInput["orderType"]>>;
type _State_cmdCreateOrderTableNumber = Assert<Assignable<typeof page.cmdCreateOrderTableNumber, string | CmdCreateOrderInput["tableNumber"]>>;
type _State_cmdCreateOrderCustomerName = Assert<Assignable<typeof page.cmdCreateOrderCustomerName, string | CmdCreateOrderInput["customerName"]>>;
type _State_cmdCreateOrderNotes = Assert<Assignable<typeof page.cmdCreateOrderNotes, string | CmdCreateOrderInput["notes"]>>;
type _State_cmdCreateOrderMenuItemId = Assert<Assignable<typeof page.cmdCreateOrderMenuItemId, string | CmdCreateOrderInput["menuItemId"]>>;
type _State_cmdCreateOrderQuantity = Assert<Assignable<typeof page.cmdCreateOrderQuantity, string | CmdCreateOrderInput["quantity"]>>;
type _State_cmdCreateOrderObservations = Assert<Assignable<typeof page.cmdCreateOrderObservations, string | CmdCreateOrderInput["observations"]>>;
type _State_cmdCreateOrderDailyShiftId = Assert<Assignable<typeof page.cmdCreateOrderDailyShiftId, string | CmdCreateOrderInput["dailyShiftId"]>>;
type _State_cmdCreateOrderOutput = Assert<Assignable<typeof page.cmdCreateOrderOutput, CmdCreateOrderOutput | null>>;
type _State_cmdCreateOrderError = Assert<Assignable<typeof page.cmdCreateOrderError, string>>;
type _State_cmdUpdateOrderStatusState = Assert<Assignable<typeof page.cmdUpdateOrderStatusState, "idle" | "loading" | "success" | "error">>;
type _State_cmdUpdateOrderStatusOrderId = Assert<Assignable<typeof page.cmdUpdateOrderStatusOrderId, string | CmdUpdateOrderStatusInput["orderId"]>>;
type _State_cmdUpdateOrderStatusStatus = Assert<Assignable<typeof page.cmdUpdateOrderStatusStatus, string | CmdUpdateOrderStatusInput["status"]>>;
type _State_cmdUpdateOrderStatusCancellationReason = Assert<Assignable<typeof page.cmdUpdateOrderStatusCancellationReason, string | CmdUpdateOrderStatusInput["cancellationReason"]>>;
type _State_cmdUpdateOrderStatusOutput = Assert<Assignable<typeof page.cmdUpdateOrderStatusOutput, CmdUpdateOrderStatusOutput | null>>;
type _State_cmdUpdateOrderStatusError = Assert<Assignable<typeof page.cmdUpdateOrderStatusError, string>>;
type _State_cmdRecordBasicPaymentState = Assert<Assignable<typeof page.cmdRecordBasicPaymentState, "idle" | "loading" | "success" | "error">>;
type _State_cmdRecordBasicPaymentOrderId = Assert<Assignable<typeof page.cmdRecordBasicPaymentOrderId, string | CmdRecordBasicPaymentInput["orderId"]>>;
type _State_cmdRecordBasicPaymentTotalAmount = Assert<Assignable<typeof page.cmdRecordBasicPaymentTotalAmount, string | CmdRecordBasicPaymentInput["totalAmount"]>>;
type _State_cmdRecordBasicPaymentPaymentMethod = Assert<Assignable<typeof page.cmdRecordBasicPaymentPaymentMethod, string | CmdRecordBasicPaymentInput["paymentMethod"]>>;
type _State_cmdRecordBasicPaymentNotes = Assert<Assignable<typeof page.cmdRecordBasicPaymentNotes, string | CmdRecordBasicPaymentInput["notes"]>>;
type _State_cmdRecordBasicPaymentOutput = Assert<Assignable<typeof page.cmdRecordBasicPaymentOutput, CmdRecordBasicPaymentOutput | null>>;
type _State_cmdRecordBasicPaymentError = Assert<Assignable<typeof page.cmdRecordBasicPaymentError, string>>;
type _Action_loadQueryOpenOrders = Assert<Assignable<typeof page.loadQueryOpenOrders, (...args: any[]) => unknown>>;
type _Handler_handleQueryOpenOrdersClick = Assert<Assignable<typeof page.handleQueryOpenOrdersClick, (...args: any[]) => unknown>>;
type _Action_loadQueryMenuItems = Assert<Assignable<typeof page.loadQueryMenuItems, (...args: any[]) => unknown>>;
type _Handler_handleQueryMenuItemsClick = Assert<Assignable<typeof page.handleQueryMenuItemsClick, (...args: any[]) => unknown>>;
type _Action_cmdCreateOrder = Assert<Assignable<typeof page.cmdCreateOrder, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderClick = Assert<Assignable<typeof page.handleCmdCreateOrderClick, (...args: any[]) => unknown>>;
type _Action_cmdUpdateOrderStatus = Assert<Assignable<typeof page.cmdUpdateOrderStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateOrderStatusClick = Assert<Assignable<typeof page.handleCmdUpdateOrderStatusClick, (...args: any[]) => unknown>>;
type _Action_cmdRecordBasicPayment = Assert<Assignable<typeof page.cmdRecordBasicPayment, (...args: any[]) => unknown>>;
type _Handler_handleCmdRecordBasicPaymentClick = Assert<Assignable<typeof page.handleCmdRecordBasicPaymentClick, (...args: any[]) => unknown>>;
type _Action_setQueryOpenOrdersDailyShiftId = Assert<Assignable<typeof page.setQueryOpenOrdersDailyShiftId, (...args: any[]) => unknown>>;
type _Handler_handleQueryOpenOrdersDailyShiftIdChange = Assert<Assignable<typeof page.handleQueryOpenOrdersDailyShiftIdChange, (...args: any[]) => unknown>>;
type _Action_setQueryOpenOrdersStatus = Assert<Assignable<typeof page.setQueryOpenOrdersStatus, (...args: any[]) => unknown>>;
type _Handler_handleQueryOpenOrdersStatusChange = Assert<Assignable<typeof page.handleQueryOpenOrdersStatusChange, (...args: any[]) => unknown>>;
type _Action_setQueryOpenOrdersOrderType = Assert<Assignable<typeof page.setQueryOpenOrdersOrderType, (...args: any[]) => unknown>>;
type _Handler_handleQueryOpenOrdersOrderTypeChange = Assert<Assignable<typeof page.handleQueryOpenOrdersOrderTypeChange, (...args: any[]) => unknown>>;
type _Action_setQueryOpenOrdersTableNumber = Assert<Assignable<typeof page.setQueryOpenOrdersTableNumber, (...args: any[]) => unknown>>;
type _Handler_handleQueryOpenOrdersTableNumberChange = Assert<Assignable<typeof page.handleQueryOpenOrdersTableNumberChange, (...args: any[]) => unknown>>;
type _Action_setQueryOpenOrdersPage = Assert<Assignable<typeof page.setQueryOpenOrdersPage, (...args: any[]) => unknown>>;
type _Handler_handleQueryOpenOrdersPageChange = Assert<Assignable<typeof page.handleQueryOpenOrdersPageChange, (...args: any[]) => unknown>>;
type _Action_setQueryOpenOrdersPageSize = Assert<Assignable<typeof page.setQueryOpenOrdersPageSize, (...args: any[]) => unknown>>;
type _Handler_handleQueryOpenOrdersPageSizeChange = Assert<Assignable<typeof page.handleQueryOpenOrdersPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setQueryMenuItemsMenuCategoryId = Assert<Assignable<typeof page.setQueryMenuItemsMenuCategoryId, (...args: any[]) => unknown>>;
type _Handler_handleQueryMenuItemsMenuCategoryIdChange = Assert<Assignable<typeof page.handleQueryMenuItemsMenuCategoryIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderOrderType = Assert<Assignable<typeof page.setCmdCreateOrderOrderType, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderOrderTypeChange = Assert<Assignable<typeof page.handleCmdCreateOrderOrderTypeChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderTableNumber = Assert<Assignable<typeof page.setCmdCreateOrderTableNumber, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderTableNumberChange = Assert<Assignable<typeof page.handleCmdCreateOrderTableNumberChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderCustomerName = Assert<Assignable<typeof page.setCmdCreateOrderCustomerName, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderCustomerNameChange = Assert<Assignable<typeof page.handleCmdCreateOrderCustomerNameChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderNotes = Assert<Assignable<typeof page.setCmdCreateOrderNotes, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderNotesChange = Assert<Assignable<typeof page.handleCmdCreateOrderNotesChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderMenuItemId = Assert<Assignable<typeof page.setCmdCreateOrderMenuItemId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderMenuItemIdChange = Assert<Assignable<typeof page.handleCmdCreateOrderMenuItemIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderQuantity = Assert<Assignable<typeof page.setCmdCreateOrderQuantity, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderQuantityChange = Assert<Assignable<typeof page.handleCmdCreateOrderQuantityChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderObservations = Assert<Assignable<typeof page.setCmdCreateOrderObservations, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderObservationsChange = Assert<Assignable<typeof page.handleCmdCreateOrderObservationsChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateOrderDailyShiftId = Assert<Assignable<typeof page.setCmdCreateOrderDailyShiftId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateOrderDailyShiftIdChange = Assert<Assignable<typeof page.handleCmdCreateOrderDailyShiftIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateOrderStatusOrderId = Assert<Assignable<typeof page.setCmdUpdateOrderStatusOrderId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateOrderStatusOrderIdChange = Assert<Assignable<typeof page.handleCmdUpdateOrderStatusOrderIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateOrderStatusStatus = Assert<Assignable<typeof page.setCmdUpdateOrderStatusStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateOrderStatusStatusChange = Assert<Assignable<typeof page.handleCmdUpdateOrderStatusStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateOrderStatusCancellationReason = Assert<Assignable<typeof page.setCmdUpdateOrderStatusCancellationReason, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateOrderStatusCancellationReasonChange = Assert<Assignable<typeof page.handleCmdUpdateOrderStatusCancellationReasonChange, (...args: any[]) => unknown>>;
type _Action_setCmdRecordBasicPaymentOrderId = Assert<Assignable<typeof page.setCmdRecordBasicPaymentOrderId, (...args: any[]) => unknown>>;
type _Handler_handleCmdRecordBasicPaymentOrderIdChange = Assert<Assignable<typeof page.handleCmdRecordBasicPaymentOrderIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdRecordBasicPaymentTotalAmount = Assert<Assignable<typeof page.setCmdRecordBasicPaymentTotalAmount, (...args: any[]) => unknown>>;
type _Handler_handleCmdRecordBasicPaymentTotalAmountChange = Assert<Assignable<typeof page.handleCmdRecordBasicPaymentTotalAmountChange, (...args: any[]) => unknown>>;
type _Action_setCmdRecordBasicPaymentPaymentMethod = Assert<Assignable<typeof page.setCmdRecordBasicPaymentPaymentMethod, (...args: any[]) => unknown>>;
type _Handler_handleCmdRecordBasicPaymentPaymentMethodChange = Assert<Assignable<typeof page.handleCmdRecordBasicPaymentPaymentMethodChange, (...args: any[]) => unknown>>;
type _Action_setCmdRecordBasicPaymentNotes = Assert<Assignable<typeof page.setCmdRecordBasicPaymentNotes, (...args: any[]) => unknown>>;
type _Handler_handleCmdRecordBasicPaymentNotesChange = Assert<Assignable<typeof page.handleCmdRecordBasicPaymentNotesChange, (...args: any[]) => unknown>>;

export {};