/// <mls fileReference="_102051_/l2/cafeFlow/web/shared/stockManagement.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowStockManagementBase } from '/_102051_/l2/cafeFlow/web/shared/stockManagement.js';
import type { AddStockItemInput, AddStockItemOutput, EditStockItemInput, EditStockItemOutput, ListStockItemsInput, ListStockItemsOutput, RegisterStockAdjustmentInput, RegisterStockAdjustmentOutput, RemoveStockItemInput, RemoveStockItemOutput } from '/_102051_/l2/cafeFlow/web/contracts/stockManagement.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowStockManagementBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_listStockItemsState = Assert<Assignable<typeof page.listStockItemsState, "idle" | "loading" | "success" | "error">>;
type _State_listStockItemsNameFilter = Assert<Assignable<typeof page.listStockItemsNameFilter, string | ListStockItemsInput["nameFilter"]>>;
type _State_listStockItemsLowStockOnly = Assert<Assignable<typeof page.listStockItemsLowStockOnly, string | ListStockItemsInput["lowStockOnly"]>>;
type _State_listStockItemsPage = Assert<Assignable<typeof page.listStockItemsPage, string | ListStockItemsInput["page"]>>;
type _State_listStockItemsPageSize = Assert<Assignable<typeof page.listStockItemsPageSize, string | ListStockItemsInput["pageSize"]>>;
type _State_listStockItemsData = Assert<Assignable<typeof page.listStockItemsData, ListStockItemsOutput>>;
type _State_addStockItemState = Assert<Assignable<typeof page.addStockItemState, "idle" | "loading" | "success" | "error">>;
type _State_addStockItemName = Assert<Assignable<typeof page.addStockItemName, string | AddStockItemInput["name"]>>;
type _State_addStockItemUnit = Assert<Assignable<typeof page.addStockItemUnit, string | AddStockItemInput["unit"]>>;
type _State_addStockItemCurrentBalance = Assert<Assignable<typeof page.addStockItemCurrentBalance, string | AddStockItemInput["currentBalance"]>>;
type _State_addStockItemMinimumLevel = Assert<Assignable<typeof page.addStockItemMinimumLevel, string | AddStockItemInput["minimumLevel"]>>;
type _State_addStockItemDescription = Assert<Assignable<typeof page.addStockItemDescription, string | AddStockItemInput["description"]>>;
type _State_addStockItemOutput = Assert<Assignable<typeof page.addStockItemOutput, AddStockItemOutput | null>>;
type _State_addStockItemError = Assert<Assignable<typeof page.addStockItemError, string>>;
type _State_editStockItemState = Assert<Assignable<typeof page.editStockItemState, "idle" | "loading" | "success" | "error">>;
type _State_editStockItemStockItemId = Assert<Assignable<typeof page.editStockItemStockItemId, string | EditStockItemInput["stockItemId"]>>;
type _State_editStockItemName = Assert<Assignable<typeof page.editStockItemName, string | EditStockItemInput["name"]>>;
type _State_editStockItemUnit = Assert<Assignable<typeof page.editStockItemUnit, string | EditStockItemInput["unit"]>>;
type _State_editStockItemMinimumLevel = Assert<Assignable<typeof page.editStockItemMinimumLevel, string | EditStockItemInput["minimumLevel"]>>;
type _State_editStockItemDescription = Assert<Assignable<typeof page.editStockItemDescription, string | EditStockItemInput["description"]>>;
type _State_editStockItemOutput = Assert<Assignable<typeof page.editStockItemOutput, EditStockItemOutput | null>>;
type _State_editStockItemError = Assert<Assignable<typeof page.editStockItemError, string>>;
type _State_removeStockItemState = Assert<Assignable<typeof page.removeStockItemState, "idle" | "loading" | "success" | "error">>;
type _State_removeStockItemStockItemId = Assert<Assignable<typeof page.removeStockItemStockItemId, string | RemoveStockItemInput["stockItemId"]>>;
type _State_removeStockItemOutput = Assert<Assignable<typeof page.removeStockItemOutput, RemoveStockItemOutput | null>>;
type _State_removeStockItemError = Assert<Assignable<typeof page.removeStockItemError, string>>;
type _State_registerStockAdjustmentState = Assert<Assignable<typeof page.registerStockAdjustmentState, "idle" | "loading" | "success" | "error">>;
type _State_registerStockAdjustmentStockItemId = Assert<Assignable<typeof page.registerStockAdjustmentStockItemId, string | RegisterStockAdjustmentInput["stockItemId"]>>;
type _State_registerStockAdjustmentQuantity = Assert<Assignable<typeof page.registerStockAdjustmentQuantity, string | RegisterStockAdjustmentInput["quantity"]>>;
type _State_registerStockAdjustmentDirection = Assert<Assignable<typeof page.registerStockAdjustmentDirection, string | RegisterStockAdjustmentInput["direction"]>>;
type _State_registerStockAdjustmentReason = Assert<Assignable<typeof page.registerStockAdjustmentReason, string | RegisterStockAdjustmentInput["reason"]>>;
type _State_registerStockAdjustmentNotes = Assert<Assignable<typeof page.registerStockAdjustmentNotes, string | RegisterStockAdjustmentInput["notes"]>>;
type _State_registerStockAdjustmentOutput = Assert<Assignable<typeof page.registerStockAdjustmentOutput, RegisterStockAdjustmentOutput | null>>;
type _State_registerStockAdjustmentError = Assert<Assignable<typeof page.registerStockAdjustmentError, string>>;
type _Action_loadListStockItems = Assert<Assignable<typeof page.loadListStockItems, (...args: any[]) => unknown>>;
type _Handler_handleListStockItemsClick = Assert<Assignable<typeof page.handleListStockItemsClick, (...args: any[]) => unknown>>;
type _Action_addStockItem = Assert<Assignable<typeof page.addStockItem, (...args: any[]) => unknown>>;
type _Handler_handleAddStockItemClick = Assert<Assignable<typeof page.handleAddStockItemClick, (...args: any[]) => unknown>>;
type _Action_editStockItem = Assert<Assignable<typeof page.editStockItem, (...args: any[]) => unknown>>;
type _Handler_handleEditStockItemClick = Assert<Assignable<typeof page.handleEditStockItemClick, (...args: any[]) => unknown>>;
type _Action_removeStockItem = Assert<Assignable<typeof page.removeStockItem, (...args: any[]) => unknown>>;
type _Handler_handleRemoveStockItemClick = Assert<Assignable<typeof page.handleRemoveStockItemClick, (...args: any[]) => unknown>>;
type _Action_registerStockAdjustment = Assert<Assignable<typeof page.registerStockAdjustment, (...args: any[]) => unknown>>;
type _Handler_handleRegisterStockAdjustmentClick = Assert<Assignable<typeof page.handleRegisterStockAdjustmentClick, (...args: any[]) => unknown>>;
type _Action_setListStockItemsNameFilter = Assert<Assignable<typeof page.setListStockItemsNameFilter, (...args: any[]) => unknown>>;
type _Handler_handleListStockItemsNameFilterChange = Assert<Assignable<typeof page.handleListStockItemsNameFilterChange, (...args: any[]) => unknown>>;
type _Action_setListStockItemsLowStockOnly = Assert<Assignable<typeof page.setListStockItemsLowStockOnly, (...args: any[]) => unknown>>;
type _Handler_handleListStockItemsLowStockOnlyChange = Assert<Assignable<typeof page.handleListStockItemsLowStockOnlyChange, (...args: any[]) => unknown>>;
type _Action_setListStockItemsPage = Assert<Assignable<typeof page.setListStockItemsPage, (...args: any[]) => unknown>>;
type _Handler_handleListStockItemsPageChange = Assert<Assignable<typeof page.handleListStockItemsPageChange, (...args: any[]) => unknown>>;
type _Action_setListStockItemsPageSize = Assert<Assignable<typeof page.setListStockItemsPageSize, (...args: any[]) => unknown>>;
type _Handler_handleListStockItemsPageSizeChange = Assert<Assignable<typeof page.handleListStockItemsPageSizeChange, (...args: any[]) => unknown>>;
type _Action_setAddStockItemName = Assert<Assignable<typeof page.setAddStockItemName, (...args: any[]) => unknown>>;
type _Handler_handleAddStockItemNameChange = Assert<Assignable<typeof page.handleAddStockItemNameChange, (...args: any[]) => unknown>>;
type _Action_setAddStockItemUnit = Assert<Assignable<typeof page.setAddStockItemUnit, (...args: any[]) => unknown>>;
type _Handler_handleAddStockItemUnitChange = Assert<Assignable<typeof page.handleAddStockItemUnitChange, (...args: any[]) => unknown>>;
type _Action_setAddStockItemCurrentBalance = Assert<Assignable<typeof page.setAddStockItemCurrentBalance, (...args: any[]) => unknown>>;
type _Handler_handleAddStockItemCurrentBalanceChange = Assert<Assignable<typeof page.handleAddStockItemCurrentBalanceChange, (...args: any[]) => unknown>>;
type _Action_setAddStockItemMinimumLevel = Assert<Assignable<typeof page.setAddStockItemMinimumLevel, (...args: any[]) => unknown>>;
type _Handler_handleAddStockItemMinimumLevelChange = Assert<Assignable<typeof page.handleAddStockItemMinimumLevelChange, (...args: any[]) => unknown>>;
type _Action_setAddStockItemDescription = Assert<Assignable<typeof page.setAddStockItemDescription, (...args: any[]) => unknown>>;
type _Handler_handleAddStockItemDescriptionChange = Assert<Assignable<typeof page.handleAddStockItemDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setEditStockItemStockItemId = Assert<Assignable<typeof page.setEditStockItemStockItemId, (...args: any[]) => unknown>>;
type _Handler_handleEditStockItemStockItemIdChange = Assert<Assignable<typeof page.handleEditStockItemStockItemIdChange, (...args: any[]) => unknown>>;
type _Action_setEditStockItemName = Assert<Assignable<typeof page.setEditStockItemName, (...args: any[]) => unknown>>;
type _Handler_handleEditStockItemNameChange = Assert<Assignable<typeof page.handleEditStockItemNameChange, (...args: any[]) => unknown>>;
type _Action_setEditStockItemUnit = Assert<Assignable<typeof page.setEditStockItemUnit, (...args: any[]) => unknown>>;
type _Handler_handleEditStockItemUnitChange = Assert<Assignable<typeof page.handleEditStockItemUnitChange, (...args: any[]) => unknown>>;
type _Action_setEditStockItemMinimumLevel = Assert<Assignable<typeof page.setEditStockItemMinimumLevel, (...args: any[]) => unknown>>;
type _Handler_handleEditStockItemMinimumLevelChange = Assert<Assignable<typeof page.handleEditStockItemMinimumLevelChange, (...args: any[]) => unknown>>;
type _Action_setEditStockItemDescription = Assert<Assignable<typeof page.setEditStockItemDescription, (...args: any[]) => unknown>>;
type _Handler_handleEditStockItemDescriptionChange = Assert<Assignable<typeof page.handleEditStockItemDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setRemoveStockItemStockItemId = Assert<Assignable<typeof page.setRemoveStockItemStockItemId, (...args: any[]) => unknown>>;
type _Handler_handleRemoveStockItemStockItemIdChange = Assert<Assignable<typeof page.handleRemoveStockItemStockItemIdChange, (...args: any[]) => unknown>>;
type _Action_setRegisterStockAdjustmentStockItemId = Assert<Assignable<typeof page.setRegisterStockAdjustmentStockItemId, (...args: any[]) => unknown>>;
type _Handler_handleRegisterStockAdjustmentStockItemIdChange = Assert<Assignable<typeof page.handleRegisterStockAdjustmentStockItemIdChange, (...args: any[]) => unknown>>;
type _Action_setRegisterStockAdjustmentQuantity = Assert<Assignable<typeof page.setRegisterStockAdjustmentQuantity, (...args: any[]) => unknown>>;
type _Handler_handleRegisterStockAdjustmentQuantityChange = Assert<Assignable<typeof page.handleRegisterStockAdjustmentQuantityChange, (...args: any[]) => unknown>>;
type _Action_setRegisterStockAdjustmentDirection = Assert<Assignable<typeof page.setRegisterStockAdjustmentDirection, (...args: any[]) => unknown>>;
type _Handler_handleRegisterStockAdjustmentDirectionChange = Assert<Assignable<typeof page.handleRegisterStockAdjustmentDirectionChange, (...args: any[]) => unknown>>;
type _Action_setRegisterStockAdjustmentReason = Assert<Assignable<typeof page.setRegisterStockAdjustmentReason, (...args: any[]) => unknown>>;
type _Handler_handleRegisterStockAdjustmentReasonChange = Assert<Assignable<typeof page.handleRegisterStockAdjustmentReasonChange, (...args: any[]) => unknown>>;
type _Action_setRegisterStockAdjustmentNotes = Assert<Assignable<typeof page.setRegisterStockAdjustmentNotes, (...args: any[]) => unknown>>;
type _Handler_handleRegisterStockAdjustmentNotesChange = Assert<Assignable<typeof page.handleRegisterStockAdjustmentNotesChange, (...args: any[]) => unknown>>;

export {};